name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Tauri dependencies
        run: >-
            sudo apt-get update &&
            sudo apt-get install -y
            libgtk-3-dev
            libayatana-appindicator3-dev
            libwebkit2gtk-4.0-dev
            webkit2gtk-driver
            xvfb

      - name: Rust stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable

      - name: Install Cargo Audit
        run: cargo install cargo-audit
    
      - name: Cargo build
        run: cargo build --release
        working-directory: ./src-tauri
        
      - name: Cargo Clippy
        run: cargo clippy --release  --verbose --all-targets --all-features
        working-directory: ./src-tauri
        
      - name: Cargo Audit
        run: cargo audit
        working-directory: ./src-tauri
