name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
    - name: Set up Rust
      uses: actions/checkout@v3
    - name: Update Rust
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    
    - name: Install Clippy
      run: rustup component add clippy
    - name: Install Cargo Audit
      run: cargo install cargo-audit
    
    - name: Build
      run: |
        cd src-tauri
        cargo build --verbose
    - name: Clippy
      run: |
        cd src-tauri
        cargo clippy --verbose --all-targets --all-features
    - name: Audit
      run: |
        cd src-tauri
        cargo audit