on: [push]

name: WebDriver

jobs:
  test:
    name: WebDriverIO Test Runner

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Tauri dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libayatana-appindicator3-dev
          libwebkit2gtk-4.0-dev
          webkit2gtk-driver
          xvfb

      - name: Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo test
        run: cargo test
        working-directory: ./src-tauri

      - name: Cargo build
        run: cargo build --release
        working-directory: ./src-tauri

      - name: Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Yarn install
        run: yarn install
        working-directory: webdriver/webdriverio

      - name: Install tauri-driver
        run: cargo add tauri-driver
        working-directory: ./src-tauri

      - name: WebdriverIO
        run: xvfb-run yarn test
        working-directory: webdriver/webdriverio